title        Arch Linux
linux        /vmlinuz-linux
initrd       /intel-ucode.img
initrd       /initramfs-linux.img
options      rd.luks.name=2057043b-d69f-423d-8b5c-a49ddadfe50a=cryptroot root=/dev/mapper/cryptroot rootflags=subvol=@ rw
