# cli.sh -- how to ask an umbriel binary to validate a config, in whichever CLI generation
# THAT binary speaks, and how to read a rejection. Sourced by common/scripts/umbriel-update;
# tests/umbriel-cli checks it against the real --help of every generation seen here, kept
# verbatim in tests/fixtures/umbriel-help/.
#
#   generation           the --help line                               spelling
#   ac83d8e, 5eb49b6     "       umbriel validate [-c <config>]"          validate
#   6bf03a0 (f66d6a8+)   "       umbriel config validate [-c <config>]"   config validate
#   b9301a6 (206038c0+)  "  config validate [-c <config>]"                config validate
#
# Mid-update the installed and the staged binary can be different generations, so each is
# asked separately, and its own --help is the signal. A binary asked in the wrong spelling
# prints its usage and exits nonzero -- by exit code the same as "configuration invalid".

# umbriel_validate_spelling <binary>: prints the words that make THIS binary validate.
# Matches the COMMAND, not the layout of the help around it. The first version matched
# "umbriel config validate", prefix included; upstream 206038c0 regrouped --help by purpose
# and dropped the prefix from each command, so b9301a6 read as the oldest generation and was
# asked `validate`, which it does not have -- the gate refused, with no verdict on the config.
# A binary that lists neither spelling is refused, never guessed at: a guess is how that
# happened.
umbriel_validate_spelling() {
  local help
  help=$("$1" --help 2>&1) || true
  if grep -qE '^[[:space:]]*(umbriel[[:space:]]+)?config[[:space:]]+validate([[:space:]]|$)' <<<"$help"; then
    echo "config validate"
  elif grep -qE '^[[:space:]]*(umbriel[[:space:]]+)?validate([[:space:]]|$)' <<<"$help"; then
    echo "validate"
  else
    return 1
  fi
}

# validate_with <binary> [config]: its verdict and exit status. When the spelling cannot be
# determined, the output starts "Usage:" -- the gate's existing sign for "the binary was not
# understood, so this is no verdict" -- and the status is 2.
validate_with() {
  local bin=$1 cfg=${2:-} spelling
  if ! spelling=$(umbriel_validate_spelling "$bin"); then
    echo "Usage: cannot tell how $bin validates a config -- its --help lists neither 'config validate' nor 'validate'"
    return 2
  fi
  if [[ $spelling == "config validate" ]]; then
    "$bin" config validate ${cfg:+-c "$cfg"}
  else
    "$bin" validate ${cfg:+-c "$cfg"}
  fi
}

# umbriel_rejection_source <palette file>  (the validate output on stdin)
# Which file the rejected keys are in, because the remedy differs completely:
#   palette  every one is in Noctalia's generated palette -- the compatibility case: the
#            INSTALLED Noctalia writes a vocabulary this umbriel does not speak. A base.toml
#            merge cannot fix it; the pair has to move (Noctalia's version, then its palette).
#   config   none is -- base.toml or the host file: bring the config forward (merge).
#   both     some of each.
#   unknown  nothing names a file (a parse error, a crash): read the output, no advice.
# Until 2026-09-28 the gate advised a merge for every rejection. On SATA caesar that sent
# a Noctalia-5.0.1 palette mismatch to --merge-config, which cannot touch that file.
umbriel_rejection_source() {
  local palette=$1 line file p=0 c=0
  while IFS= read -r line; do
    [[ $line =~ ^(warning|error):\ (/[^:]+): ]] || continue
    file=${BASH_REMATCH[2]}
    if [[ $file == "$palette" ]]; then ((p++)); else ((c++)); fi
  done
  if ((p && c)); then echo both
  elif ((p)); then echo palette
  elif ((c)); then echo config
  else echo unknown; fi
}

# umbriel_rejection_advice <palette file> <source>: what to do, by umbriel_rejection_source.
umbriel_rejection_advice() {
  local palette=$1 src=$2
  case $src in
    palette|both)
      echo "Noctalia's palette ($palette) is rejected: it was generated by the INSTALLED"
      echo "Noctalia ($(pacman -Q noctalia 2>/dev/null || echo 'noctalia: not installed')), whose umbriel vocabulary this build does not speak."
      echo "That is the compatibility case -- a base.toml merge cannot fix it. Move the pair:"
      echo "    sudo pacman -Syu        a Noctalia whose palette speaks this umbriel"
      echo "    log out and back in     so the NEW Noctalia rewrites $palette"
      echo "Then re-run this command. The built package is kept, so the rebuild is cheap." ;;&
    both)
      echo ;;&
    config|both)
      echo "base.toml or the host file is rejected: the breaking-change case. Bring the config forward:"
      echo "    umbriel-update --merge-config --apply"
      echo "Then re-run --apply. The built package is kept, so the rebuild is cheap." ;;
    unknown)
      echo "The output names no config file, so there is no advice to give: read it above." ;;
  esac
}
